services:
  postgres:
    image: postgres:18
    container_name: musereview-postgres
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_DB: mr_db
      POSTGRES_USER: musereview
      POSTGRES_PASSWORD: musereview1234
    volumes:
      - musereview-postgres-data:/var/lib/postgresql

  redis:
    image: redis:7.4-alpine
    container_name: musereview-redis
    ports:
      - "127.0.0.1:6379:6379"
    command: ["redis-server", "--appendonly", "no"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  musereview-postgres-data:
