services:
  postgres:
    image: postgres:18
    container_name: musereview-postgres
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_DB: mr_db
      POSTGRES_USER: musereview
      POSTGRES_PASSWORD: musereview1234
    volumes:
      - musereview-postgres-data:/var/lib/postgresql

volumes:
  musereview-postgres-data:
