spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  flyway:
    enabled: false

oauth:
  kakao:
    redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/api/auth/kakao/callback}
  google:
    redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/api/auth/google/callback}

ai:
  internal:
    base-url: ${AI_INTERNAL_BASE_URL}

decorator:
  datasource:
    p6spy:
      enable-logging: true
      logging: slf4j
      multiline: true

logging:
  level:
    root: info
    org.hibernate.SQL: debug
